name: Bump Homebrew formula

on:
  push:
    tags: '*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          tap: ablinov/homebrew-made
          formula: declutter
