name: Bump Homebrew formula

on:
  push:
    tags: '*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1.6
        with:
          formula-name: declutter
          homebrew-tap: ablinov/homebrew-made
        env:
          COMMITTER_TOKEN: ${{ secrets.TOKEN }}
