name: Bump Homebrew formula

on:
  push:
    tags: '*'

jobs:
  homebrew:
    - name: Update Homebrew formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{secrets.TOKEN}}
        tap: ablinov/homebrew-made
        formula: declutter
